language: python
python:
  - "3.6"
services:
  - docker
before_install:
- docker pull node
- docker pull redis
- docker pull postgres
- docker pull python:3.6
- docker pull nginx
script:
  - bash ddo.sh --make && bash ddo.sh --run && bash ddo.sh --stop-all