REQUIREMENTS=[
	'channels',
	'channels_redis',
	'psycopg2',
	'Pillow',
]

PROJECT_NAME='exemplo'

PYTHON_VERSION='3.6'

DATABASE='postgres'

'''
ENVIROMENTS
	POSTGRESS:
		USER_NAME = POSTGRES_USER
		PASSWORD_NAME = POSTGRES_PASSWORD
		DB_NAME = POSTGRES_DB
	MYSQL:
		USER_NAME = MYSQL_USER
		PASSWORD_NAME = MYSQL_PASSWORD
		DB_NAME = MYSQL_DATABASE
		ROOT_PASSWORD_NAME = MYSQL_ROOT_PASSWORD
	MONGO:
		USER_NAME = MONGO_INITDB_ROOT_USERNAME
		PASSWORD_NAME = MONGO_INITDB_ROOT_PASSWORD
'''
DATABASE_ENVIROMENTS={
	'DATABASE_USER_VALUE':'exemplouser',
	'DATABASE_USER_NAME':'POSTGRES_USER',

	'DATABASE_PASSWORD_VALUE':'exemplopass',
	'DATABASE_PASSWORD_NAME':'POSTGRES_PASSWORD',

	'DATABASE_DB_VALUE':'exemplodb',
	'DATABASE_DB_NAME':'POSTGRES_DB',
}
DATABASE_ROOT={
	'SOURCE':'./databases',
	'DESTINATION':'/var/lib/postgresql/data',
}

LOGS_ROOT='/logs'

WEB_PORT='8000'

WEB_ENVIROMENT={
	'REDIS_URL':'redis://redis:6379/0',
	'REDIS_URL2':'redis://redis:6379/0',
}


CONTAINERS=['redis']


DOCKER_COMPOSE_VERSION='3'
