# Generated by Django 2.0.5 on 2018-05-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20180525_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default=1, upload_to='fotos'),
            preserve_default=False,
        ),
    ]
